"""Adding Contribution

Revision ID: 479bf6079208
Revises: 
Create Date: 2024-01-16 10:42:27.744263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479bf6079208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wd_item', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('lang_code', sa.String(length=150), nullable=True),
    sa.Column('edit_type', sa.String(length=150), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribution_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribution_id'))

    op.drop_table('contribution')
    # ### end Alembic commands ###
